# Generated by Django 6.0 on 2025-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_repairticket_reported_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
